export const LOADER_SHOW = 'LOADER_SHOW';
export const LOADER_HIDE = 'LOADER_HIDE';
export const LOADING_INIT = 'LOADING_INIT';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

//country
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
export const GET_COUNTRY_ERROR = 'GET_COUNTRY_ERROR';
//CancerType
export const GET_DIAGNOSISMUTATION_SUCCESS = 'GET_DIAGNOSISMUTATION_SUCCESS';
export const GET_STAGE_SUCCESS = 'GET_STAGE_SUCCESS';
export const GET_CANCERTYPE_ERROR = 'GET_CANCERTYPE_ERROR';

export const GET_HASHTAG_SUCCESS = 'GET_HASHTAG_SUCCESS';
//Login page
export const LOGGED_IN_SUCCESS = 'LOGGED_IN_SUCCESS';
export const LOGGED_IN_ERROR = 'LOGGED_IN_ERROR';
//OTP Page
export const VERIFY_ACCESSCODE_SUCCESS = 'VERIFY_ACCESSCODE_SUCCESS';
export const VERIFY_ACCESSCODE_ERROR = 'VERIFY_ACCESSCODE_ERROR';
//Forget Password Page
export const FORGETPASSWORD_SUCCESS = 'FORGETPASSWORD_SUCCESS';
export const FORGETPASSWORD_ERROR = 'FORGETPASSWORD_ERROR';
//SignUp Page
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_ERROR = 'AUTH_SIGNUP_ERROR';

//Menu
export const ALL_TARGETEDTHERAPY_SUCCESS = 'ALL_TARGETEDTHERAPY_SUCCESS';
export const GETONCONEWS_SUCCESS = 'GETONCONEWS_SUCCESS';
export const GETALLKNOWYOURDNA_SUCCESS = 'GETALLKNOWYOURDNA_SUCCESS';
export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
export const JOURNAL_SUCCESS = 'JOURNAL_SUCCESS';
export const GETALLJOURNAL_SUCCESS = 'GETALLJOURNAL_SUCCESS';
export const GETFILTERJOURNAL_SUCCESS = 'GETFILTERJOURNAL_SUCCESS';
export const WORKBOOK_SUCCESS = 'WORKBOOK_SUCCESS';
export const GETALLWORKBOOK_SUCCESS = 'GETALLWORKBOOK_SUCCESS';
export const GETAPPOINTMENT_QUESTIONS_SUCCESS = 'GETAPPOINTMENT_QUESTIONS_SUCCESS';
export const GETFILTERWORKBOOK_SUCCESS = 'GETFILTERWORKBOOK_SUCCESS';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const SYMPTOM_SUCCESS = 'SYMPTOM_SUCCESS';
export const GETSYMPTOMLIST_SUCCESS = 'GETSYMPTOMLIST_SUCCESS';
export const GETALLSYMPTOMS_SUCCESS = 'GETALLSYMPTOMS_SUCCESS';
export const GETFILTERSYMPTOMS_SUCCESS = 'GETFILTERSYMPTOMS_SUCCESS';
export const GETALLSYMPTOMMAIL_SUCCESS = 'GETALLSYMPTOMMAIL_SUCCESS';

export const GET_VOICE_RECORDINGS = 'GET_VOICE_RECORDINGS';

export const GET_APPOINTMENT_BOOKINGS = 'GET_APPOINTMENT_BOOKINGS';
export const GET_AVAILABILITY_DATE = 'GET_AVAILABILITY_DATE';
export const APPOINTMENT_BOOKINGS = 'APPOINTMENT_BOOKINGS';


//Auth Token
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS';
export const GET_FOLDER_NAMES_SUCCESS = 'GET_FOLDER_NAMES_SUCCESS';
export const GET_USER_FILES_SUCCESS = 'GET_USER_FILES_SUCCESS';
export const GET_USER_SHAREFILES_SUCCESS = 'GET_USER_SHAREFILES_SUCCESS';
export const GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS';
export const SHARE_FILES_SUCCESS = 'SHARE_FILES_SUCCESS';
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS';
export const GET_OTHERS_PROFILE_SUCCESS = 'GET_OTHERS_PROFILE_SUCCESS';
export const GET_PATIENTS_FILES_SUCCESS = 'GET_PATIENTS_FILES_SUCCESS';
export const PROFILEPIC_UPLOAD_SUCCESS = 'PROFILEPIC_UPLOAD_SUCCESS';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';

export const GET_HASHTAG_HISTORY = 'GET_HASHTAG_HISTORY';

//Error
export const API_ERROR = 'API_ERROR';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';

export const CREATE_FEED = 'CREATE_FEED';
export const GET_ALL_FEEDS = 'GET_ALL_FEEDS';
export const GET_POST_COMMENTS = 'GET_POST_COMMENTS';
export const SET_POST_ACTIONS = 'SET_POST_ACTIONS';


export const CREATE_THERAPY_FEED = 'CREATE_THERAPY_FEED';
export const GET_THERAPY_FEEDS = 'GET_THERAPY_FEEDS';
export const SET_THERAPY_POST_ACTIONS = 'SET_THERAPY_POST_ACTIONS';





