const Choose_Login_Screen = {
  login_app_title_txt: 'The all in one platform for the Cancer Patients',
  login_main_title_txt:
    'Welcome to Personalized and Targeted Cancer Therapy Community',
  login_subtitle_txt: 'Conquering Cancer Together',
  login_signup_txt:
    'Signup with a personal email address or your Facebook, Twitter, or Gmail account',
  login_email_txt: 'Email',
  login_gmail_txt: 'Gmail',
  login_facebook_txt: 'Facebook',
  login_twitter_txt: 'Twitter',
  signup_title_txt: 'Do not have an account ?',
  signup_txt: 'Sign Up',
  bank_txt: 'Bank Details',
};

const Login_Screen = {
  login_title_txt: 'LOGIN',
  email_placeholder_txt: 'Email',
  password_placeholder_txt: 'Password',
  forgot_password_txt: 'Forgot Password?',
  login_btn_txt: 'Login',
  submit_error_txt: 'Please Enter UserName and Password',
};

const Forget_Password = {
  forget_password_title_txt: 'Forgot Password',
  email_title_txt: 'Email',
  submit_btn_txt: 'Submit',
  cancel_btn_txt: 'Cancel',
  submit_error_txt: 'Please Enter Email Address',
};

const Reset_Password = {
  reset_password_title: 'Create New Password',
  password_input_placeholder: 'New Password',
  confirm_password_input_placeholder: 'Re type New Password',
  pwd_match_error_txt: 'The passwords does not match',
  submit_btn_txt: 'Update Password',
};

const Signup_Screen = {
  screen_01: {
    username_input_placeholder: 'User Name',
    email_input_placeholder: 'Email',
    mobile_input_placeholder: 'Phone Number',
    country_select_placeholder: 'Choose your country',
    state_select_placeholder: 'Choose Your State',
    password_input_placeholder: 'Password',
    confirm_password_input_placeholder: 'Re type Password',
    pwd_match_error_txt: 'The passwords does not match',
    touchID_txt: 'Enable Touch ID',
    signup_txt: 'Sign Up',
  },
  screen_02: {
    patient_txt: 'Patient',
    physician_txt: 'Physician',
    advocacy_txt: 'Advocacy/Caregiver',
    cancer_title_txt: 'Choose your Cancer Type',
    cancertype_select_placeholder: 'Select a CancerType',
    markers_title_txt: 'Choose Markers/Mutations',
    markers_select_placeholder: 'Select a Markers/Mutations',
    entrolled_title_txt: 'Are you enrolled in clinical trial',
    entrolled_input_placeholder: 'Name of the trial',
    entrolled_error: 'Please Enter Clinical Trial Name',
    stage_title_txt: 'Choose your Stage',
    stage_select_placeholder: 'Select a Stage',
    firstname_input_placeholder: 'First Name',
    lastname_input_placeholder: 'Last Name',
    license_input_placeholder: 'Enter License Number',
    specialization_title_txt: 'SPECIALIZATION',
    specialization_select_txt: 'Select a Specialization',
    affiliation_input_placeholder: 'Please enter a Affiliation',
    advocacyname_input_placeholder: 'Please enter Advocacy or Foundation Name',
    terms_error_txt: 'Please select terms and condition',
    trail_error_txt: 'Please Enter Clinical Trial Name',
  },
  screen_03: {
    accName_input_placeholder: 'Account Holder Name',
    bankName_input_placeholder: 'Bank Name',
    accNo_input_placeholder: 'Account Number',
    branchName_input_placeholder: 'Branch',
    ifscCode_input_placeholder: 'IFSC Code',
    UPI_input_placeholder: 'UPI ID',
    MMID_input_placeholder: 'MMID',
  },
  modalTitle_Txt: 'Mail Sent!',
  modalSubtitle_Txt:
    'A confirmation email was sent your account at contactcureoncoApp@gmail.com. You must follow the instructions in the email before your account can be activated',
  modalBtn_Txt: 'Ok',
  submit_txt: 'Submit',
};

const Dash_Board = {
  home: {
    dashboard_title_txt: 'CureOnco',
    header_title_txt: 'Cureonco',
    home_txt: 'Home',
    profile_txt: 'My Profile',
    journals_txt: 'My Journal',
    voiceRecord_txt: 'Voice Record',
    feedback_txt: 'Feedback',
    logout_txt: 'Logout',
    privacy_txt: 'Privacy Policy',
    following_txt: 'Following',
    followers_txt: 'Followers',
    posts_txt: 'Posts',
    terms_txt: 'Terms & Conditions',
    use_txt: 'How To Use',
    about_txt: 'About Us',
    patients_forum_txt: 'Patients Forum',
    appointment_book_txt: 'Appointment Booking',
    appointments_txt: 'Appointments',
    onco_news_txt: 'Onco News',
    closed_community_txt: 'Closed Community',
    targeted_therapy_txt: 'Targeted Therapy',
    symptom_log_txt: 'Symptoms Log',
    journal_txt: 'Journals',
    dna_sequence_txt: 'DNA Sequence',
    my_document_txt: 'Documents',
    patient_files_txt: 'Patient Files',
    workbook_txt: 'Appointments WorkBook',
    calendar_txt: 'Calendar',
    know_txt: 'Know your DNA',
    search_txt: 'Search',
    find_trail_match_txt: 'Find your Clinical Trail Match',
    trail_match_txt: 'Trail Match',
    recording_txt: 'Voice Recording',
    notification_txt: 'Notification',
  },
  closedCommunity: {
    closed_group_chat_txt: 'Group Chat',
    closed_create_group_title_txt:
      'Create your own Cancer Community Group here',
    closed_create_group_btn_txt: 'Create a Group',
    closed_adult_community_txt: 'Adult Cancer Community',
    closed_pediatric_community_txt: 'Pediatric Cancer  Community',
    closed_cup_community_txt: 'Cancer of Unknown Primary (CUP)',
    closed_mutation_community_txt: 'Mutation Community',
    closed_private_chat_txt: 'Private Chat',
    closed_private_search_placeholder: 'Search User to chat',
    closed_viewBtn_txt: 'View Group',
    closed_joinBtn_txt: 'Join',
    create_new_group_txt: 'New Group',
    user_txt: 'Users',
    search_user_placeholder: 'Search User',
    select_user_header_txt: 'Select User',
    create_group_txt: 'Create Group',
    group_chat_txt: 'Group Chat',
    private_chat_txt: 'Private Chat',
    chat_room_title_placeholder: 'Group Name',
    chat_room_desc_placeholder: 'Group Description',
    grouptype_title_txt: 'Group Type :',
    add_people_txt: 'Participants',
    add_admin_txt: 'Admin',
    update_group_txt: 'Update a Group',
    update_group_title_txt: 'Update Group',
    group_info_txt: 'Group Info',
    chat_room_users_txt: 'Chat Room Users',
    chat_room_admin_txt: 'Chat Room Admin',
    delete_group_txt: 'Delete Group',
    exit_group_txt: 'Exit Group',
    admin_group_txt: 'Admin',
  },
  symptoms: {
    title_txt: 'How are you feeling today?',
    add_title_txt: 'Symptoms Log',
    listlog_txt: 'Symptom Log on',
    share_email_placeholder: 'Enter Email Id',
    share_email_error_txt: 'Please Enter valid Email id',
    send_email_btn_txt: 'Send Email',
    header_add_title_txt: 'Add Symptoms Log',
    drug_input_placeholder: 'Enter Drug Name or Clinical Trail',
    email_title_txt: 'Symptom Log',
    notes_txt: 'Enter any notes',
    drugname_error_txt: 'Enter Drug Name',
    save_btn_txt: 'Save Symptoms',
  },
  journals: {
    add_journal_txt: 'Add Journal Entry',
    journal_physicianname_txt: 'Physician Name :',
    journal_fellabout_txt:
      'Fell about your Diagnosis, Treatment and Symptoms :',
    add_journal_header_txt: 'Add Journal',
    add_journal_physician_placeholder: 'Enter Physician Name',
    add_journal_fellabout_placeholder:
      'How you fell about your Diagnosis, treatment and symptoms',
    save_journal_btnTxt: 'Save',
    submit_journal_btnTxt: 'Submit',
  },
  workbook: {
    add_workbook_txt: 'Add Workbook',
    question_select_title_txt: 'Appointment Questions',
    question_select_placeholder: 'Appointment Questions',
    workbook_appintmentDate_txt: 'Appointment Date :',
    workbook_physicianname_txt: 'Physician Name :',
    workbook_visit_txt: 'Purpose Of Visit :',
    workbook_questions_txt: ' Questions To Doctor :',
    workbook_notes_txt: 'Notes :',
    add_workbook_header_txt: 'Add Appointment Note',
    add_workbook_date_placeholder: 'Enter Appointment Date',
    add_workbook_physician_placeholder: 'Enter Physician Name',
    add_workbook_visit_placeholder: 'Enter Purpose Of Visit',
    add_workbook_questions_placeholder: 'Question to Physician',
    add_workbook_notes_placeholder: 'Notes',
    save_workbook_btnTxt: 'Save',
    submit_workbook_btnTxt: 'Submit',
  },
  trailmatch: {
    drug_name_txt: 'DRUG NAME',
    drug_placeholder_txt: 'Enter a Drug Name',
    searchBtn_Txt: 'Search',
  },
  AppointmentBooking: {
    appointment_txt: 'Book Appointment',
    search_doctor_placeholder: 'Search Doctors',
    confirm_date_txt: 'Confirm Date',
    cancel_txt: 'Cancel',
    confirm_book_txt: 'Book Appointment',
    back_txt: 'Back',
    book_appointment_txt: 'Book Appointment',
    schedule_txt: 'Schedules',
    reschedule_txt: 'Reschedule',
  },
  Appointments: {
    accept_txt: 'Accept',
    decline_txt: 'Reject',
    command_placeholder: 'Enter Commants',
    command_txt: 'Commants : ',
    upcoming_txt: 'UpComing',
    completed_txt: 'Visits',
    cancelled_txt: 'Cancelled',
    accepted_txt: 'Accepted',
    rejected_txt: 'Rejected',
    reschedule_book_txt: 'Reschedule',
  },
  TargetedTherapy: {
    target_title_txt: 'Target/Marker',
    target_name_txt: 'Select a Target/Marker',
    drug_name_title_txt: 'Drug Name',
    cancerType_txt: 'Cancer Type :',
    targeted_txt: 'Target/Marker :',
  },
  feedback: {
    feedback_header_txt: 'FeedBack',
    feedback_placeholder: 'Type your feedback',
    submit_error_txt: 'Please enter the your feedback',
    submitBtn_Txt: 'Submit',
    modalTitle_Txt: 'Thanks for being awesome!',
    modalSubtitle_Txt:
      'We have received your message and would like to thank you for writing to us. If your inquiry is urgent, please use the telephone number listed below to talk to one of our staff members.',
    modalBtn_Txt: 'Ok',
  },
  MyDocument: {
    user_document_txt: 'User Documents',
    user_share_document_txt: 'User Shared Documents',
    QR_code_document_txt: 'QR Code',
    category_Folder_txt: 'Category Folder',
    submitBtn_Txt: 'Submit',
    modalTitle_Txt: 'Thanks for being awesome!',
    modalSubtitle_Txt:
      'We have received your message and would like to thank you for writing to us. If your inquiry is urgent, please use the telephone number listed below to talk to one of our staff members.',
    modalBtn_Txt: 'Ok',
  },
  profile: {
    following_txt: 'Following',
    followers_txt: 'Followers',
    posts_txt: 'Posts',
    profile_about_placeholder: 'About',
    profile_about_error_txt: 'Enter About',
    profile_saveBtn_Txt: 'Update',
  },
  search: {
    search_header_txt: 'Search',
    people_txt: 'People',
    post_txt: 'Post',
    search_placeholder_txt: 'Search',
  },
  post: {
    post: 'Post',
    postItemCommentsTxt: 'Comments',
    postItemLikesTxt: 'Likes',
    postItemLikeTxt: 'Like',
    postItemHugTxt: 'Hug',
    postItemCareTxt: 'Care',
    postItemCommentTxt: 'Comment',
    postCommentsTxt: 'COMMENTS',
    postReactionsTxt: 'REACTIONS',
    postItemReplyTxt: 'Reply',
  },
  permission: {
    title: 'Cureonco App Camera Permission',
    message:
      'Cureonco App needs access to your camera so you can take awesome pictures.',
    btnNeutral: 'Ask Me Later',
    btnNegative: 'Cancel',
    btnPositive: 'OK',
  },
  voiceRecording: {
    title_txt: 'Recording',
    save_btn_txt: 'Save',
    cancel_btn_txt: 'Cancel',
    btnNegative: 'Cancel',
    btnPositive: 'OK',
  },
};

const Select_Box = {
  mutation_placeholder_txt: 'Enter your Mutation or Fusion',
  save_btn: 'Save',
};

const bottom_menu = {
  home: 'Home',
  group_me: 'Closed Community',
  pm: 'Targeted Therapy,',
  search: 'Search',
  symptom: 'Symptoms Log',
  notification: 'Notification',
};

const group_me = {
  title: 'Closed Community',
  group_button: 'Join',
  create_chat_room_title: 'Create Community',
  create_chat_room_01_textinput: 'Title',
  create_chat_room_02_textinput: 'Description',
  chatroomlist: 'Chat Lists',
  chatpanel: 'Chat Room',
};

const ErrorTxts = {
  Login_Error: {
    emailError: 'Please Enter the Email',
    emailValidError: 'Please Enter the Valid Emaild',
    passwordError: 'Please Enter the Password',
    confirmPasswordError: 'Please Enter the Confirm Password',
    passwordShortError: 'Password is short',
    passwordLongError: 'Password too long',
  },
  Register_Error: {
    nameError: 'Please Enter the User Name',
    emailError: 'Please Enter the Email',
    emailValidError: 'Please Enter the Valid Email',
    countryError: 'Please Choose Your Country',
    stateError: 'Please Choose Your State',
    phoneError: 'Please Enter the Phone Number',
    passwordError: 'Please Enter the Password',
    confirmPasswordError: 'Please Enter the Confirm Password',
    passwordShortError: 'Password is short',
    passwordLongError: 'Password too long',
  },
  UserType_Error: {
    cancerTypeError: 'Please Select a CancerType',
    markersError: 'Please Select a Markers/Mutations',
    trailError: 'Please Enter the Clinical Trail',
    stageError: 'Please Select a Stage',
    firstNameError: 'Please Enter the First Name',
    lastNameError: 'Please Enter the Last Name',
    licenseError: 'Please Enter the License NUmber',
    specializationError: 'Please Select a Specialization',
    affiliationError: 'Please Enter the Affiliation',
    patientNameError: 'Please Enter the Patient Name',
    relationshipError: 'Please Enter the Relationship',
    advocayError: 'Please Enter the Advocay or Fountation',
  },
};

export {
  Choose_Login_Screen,
  Login_Screen,
  Signup_Screen,
  Dash_Board,
  Select_Box,
  Forget_Password,
  Reset_Password,
  bottom_menu,
  group_me,
  ErrorTxts,
};
