const ScreenNames = {
  stackNavigation: {
    Splash: 'Splash',
    OnBoard: 'OnBoard',
    Login: 'Login',
    ChangePassword: 'ChangePassword',
    OTP: 'OTP',
    Signup: 'Signup',
    UserType: 'UserType',
    DashBoard: 'DashBoard',
    Feedback: 'Feedback',
    Journals: 'Journals',
    DocumentsShare: 'DocumentsShare',
    MyDocuments: 'MyDocuments',
    Documents: 'Documents',
    AppointmentWorkBook: 'AppointmentWorkBook',
    KnowYourDNA: 'KnowYourDNA',
    CalendarBooking: 'CalendarBooking',
    Search: 'Search',
    ClinicalTrail: 'ClinicalTrail',
    OncoNews: 'OncoNews',
    UserProfile: 'UserProfile',
    OthersProfile: 'OthersProfile',
    BankDetails: 'BankDetails',
    EditProfile: 'EditProfile',
    Follow: 'Follow',
    DoctorProfile: 'DoctorProfile',
    JournalHistory: 'JournalHistory',
    AddJournal: 'AddJournal',
    WorkbookList: 'WorkbookList',
    AddWorkbook: 'AddWorkbook',
    SymptomsLog: 'SymptomsLog',
    AddSymptom: 'AddSymptom',
    PatientPosts: 'PatientPosts',
    CreatePost: 'CreatePost',
    Comments: 'Comments',
    VoiceRecording: 'VoiceRecording',
    SharedFiles: 'SharedFiles',
    AppointmentBooking: 'AppointmentBooking',
    Appointments: 'Appointments',
    CreateGroupChat: 'CreateGroupChat',
    ViewGroupChat: 'ViewGroupChat',
    Chat: 'Chat',
    MenuWebView: 'MenuWebView',
    Track: 'Track',
  },
  tabNavigation: {
    HomeMenu: 'HomeMenu',
    PatientForum: 'PatientForum',
    ClosedCommunity: 'ClosedCommunity',
    TargetedTherapy: 'TargetedTherapy',
    Symptoms: 'Symptoms',
    Notification: 'Notification',
  },
  topTabNavigation: {
    Schedules: 'Schedules',
    BookAppointment: 'BookAppointment',
    GroupChat: 'Group Chat',
    PrivateChat: 'Private Chat',
  },
};
export default ScreenNames;
