import {StyleSheet, Dimensions} from 'react-native';
import appStyles from '../../../assets/Styles/AppStyles';
import {colors, fonts} from '../../../themes/themes';
import {
  convertToDeviceResolution,
  scaledHeight,
  scaledWidth,
} from '../../../utils/Resolution';

const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  profileView: {
    marginLeft: scaledWidth(15),
    flexDirection: 'row',
    marginTop: scaledHeight(20),
    alignItems: 'center',
  },
  nameTxt: {
    fontSize: 15,
    marginLeft: scaledWidth(8),
    color: '#0F0F0F',
    fontFamily: fonts.semi_bold,
  },
  emailTxt: {
    fontSize: 14,
    marginLeft: scaledWidth(8),
    color: '#0F0F0F',
    fontFamily: fonts.regular,
  },
  trackTopView: {
    borderRadius: 10,
    marginLeft: scaledWidth(15),
    marginRight: scaledWidth(15),
    marginBottom: scaledHeight(10),
    ...appStyles.boxShadow,
    backgroundColor: colors.white,
  },
  trackTouchView: {
    flex: 1,
    flexDirection: 'row',
    marginLeft: scaledWidth(20),
    marginRight: scaledWidth(20),
    marginBottom: scaledHeight(20),
    marginTop: scaledHeight(20),
  },
  trackTouch: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0, 78, 139, 0.15)',
    paddingBottom: scaledHeight(5),
    paddingTop: scaledHeight(5),
    paddingleft: scaledWidth(50),
    paddingRight: scaledWidth(15),
    alignItems: 'center',
    borderRadius: 10,
    alignSelf: 'flex-end',
  },
  tracTxt: {
    fontFamily: fonts.medium,
    fontSize: 15,
    color: '#004E8B',
    marginLeft: scaledWidth(5),
  },
  feelingTxt: {
    fontFamily: fonts.regular,
    fontSize: 15,
    color: '#0F0F0F',
    flex: 1,
  },
  trackIcon: {
    marginLeft: scaledWidth(15),
  },
  feelingView: {
    flexDirection: 'row',
    flex: 1,
    marginLeft: scaledWidth(20),
    marginRight: scaledWidth(20),
    marginBottom: scaledHeight(20),
  },
  feelingTouch: {
    flex: 1,
    alignItems: 'center',
  },
  feelingText: {
    fontFamily: fonts.regular,
    fontSize: 12,
    color: '#0F0F0F',
    marginTop: scaledHeight(5),
  },
  serviceTxt: {
    fontFamily: fonts.semi_bold,
    fontSize: 16,
    color: '#0F0F0F',
    marginLeft: scaledHeight(20),
    marginTop: scaledHeight(10),
  },
  menuIconView: {
    flexDirection: 'row',
    marginTop: scaledHeight(5),
    marginLeft: scaledWidth(10),
    marginRight: scaledWidth(10),
  },
  menuIconTouch: {
    alignItems: 'center',
    justifyContent: 'center',
    margin: 5,
    flex: 1,
    borderWidth: 0.5,
    borderRadius: 5,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    backgroundColor: '#FEFEFE',
    paddingBottom: scaledHeight(10),
    paddingTop: scaledHeight(10),
    paddingLeft: scaledWidth(5),
    paddingRight: scaledWidth(5),
  },
  menuIcon: {
    width: convertToDeviceResolution(15),
    height: convertToDeviceResolution(15),
  },
  menuTxt: {
    fontFamily: fonts.semi_bold,
    fontSize: 12,
    color: '#004E8B',
    textAlign: 'center',
    marginTop: scaledHeight(10),
  },
  appointmentTopView: {
    flexDirection: 'row',
    backgroundColor: '#F2F6F9',
    marginLeft: scaledWidth(15),
    marginRight: scaledWidth(15),
    marginTop: scaledHeight(10),
    borderRadius: 5,
  },
  dateView: {
    backgroundColor: '#FFF',
    paddingBottom: scaledHeight(10),
    paddingTop: scaledHeight(10),
    paddingLeft: scaledWidth(15),
    paddingRight: scaledWidth(15),
    marginTop: scaledHeight(10),
    marginBottom: scaledHeight(10),
    marginLeft: scaledWidth(10),
    borderRadius: 5,
    alignItems: 'center',
  },
  monthTxt: {
    fontFamily: fonts.bold,
    fontSize: 17,
    color: '#545454',
  },
  dateTxt: {
    fontFamily: fonts.semi_bold,
    fontSize: 24,
    color: '#004E8B',
    marginTop: scaledHeight(5),
  },
  doctorView: {
    flex: 1,
    justifyContent: 'center',
    marginLeft: scaledWidth(5),
  },
  doctorNameTxt: {
    fontFamily: fonts.semi_bold,
    fontSize: 20,
    color: '#545454',
  },
  timeTxt: {
    fontFamily: fonts.semi_bold,
    fontSize: 14,
    color: '#737B7D',
    marginTop: scaledHeight(5),
  },
  iconView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: scaledWidth(10),
  },
  callIcon: {
    borderRadius: 100,
    width: scaledWidth(45),
    height: scaledHeight(50),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    ...appStyles.boxShadow,
    marginRight: scaledWidth(10),
  },
  videoIcon: {
    borderRadius: 100,
    width: scaledWidth(45),
    height: scaledHeight(50),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    ...appStyles.boxShadow,
  },
  journalTopView: {
    height: scaledHeight(200),
    width: scaledWidth(250),
    marginRight: scaledWidth(10),
  },
  titleTxt: {
    fontFamily: fonts.semi_bold,
    fontSize: 16,
    color: '#0F0F0F',
    marginLeft: scaledWidth(20),
    marginTop: scaledHeight(10),
  },
  descpTxt: {
    fontFamily: fonts.semi_bold,
    fontSize: 16,
    color: '#0F0F0F',
    marginLeft: scaledWidth(20),
    marginTop: scaledHeight(10),
  },
  journalDateTxt: {
    fontFamily: fonts.semi_bold,
    fontSize: 16,
    color: '#0F0F0F',
    marginLeft: scaledWidth(20),
    marginTop: scaledHeight(10),
  },
  listContainer: {
    marginTop: scaledHeight(10),
    marginLeft: scaledWidth(15),
    marginRight: scaledWidth(15),
    paddingLeft: scaledWidth(15),
    paddingRight: scaledWidth(15),
    paddingBottom: scaledWidth(15),
    backgroundColor: '#FEFEFE',
  },
  topicView: {
    flexDirection: 'row',
    marginTop: scaledHeight(10),
  },
  itemTopicTxt: {
    flex: 1,
    color: colors.black,
    fontSize: 12,
    fontFamily: fonts.semi_bold,
  },
  itemHourTxt: {
    flex: 1,
    color: colors.black,
    fontSize: 12,
    fontFamily: fonts.regular,
    textAlign: 'right',
    marginRight: 10,
  },
  listItemTitle: {
    color: '#545454',
    fontSize: 15,
    width: width / 1.55,
    marginRight: scaledWidth(5),
    fontFamily: fonts.medium,
  },
  listItemDesc: {
    color: '#747D8C',
    fontSize: 12,
    marginRight: scaledWidth(5),
    marginTop: scaledHeight(10),
    fontFamily: fonts.semi_bold,
  },
  webView: {
    position: 'relative',
    height: '100%',
  },
  linkTxt: {
    textDecorationLine: 'underline',
    color: colors.blue,
    marginTop: scaledHeight(5),
  },
  listIcon: {
    width: scaledWidth(70),
    height: scaledHeight(70),
    marginRight: scaledWidth(10),
  },
  listStyle: {
    marginBottom: scaledHeight(10),
  },
  listView: {
    flex: 1,
    marginTop: scaledHeight(10),
    marginBottom: scaledHeight(185),
  },
  journalList: {
    marginLeft: scaledWidth(10),
    marginTop: scaledHeight(10),
    marginRight: scaledWidth(10),
  },
  sectionItemSep: {
    height: scaledHeight(1),
    width: '90%',
    marginLeft: scaledWidth(15),
    backgroundColor: 'rgba(224, 224, 224, 0.5)',
  },
  seeMoreTxt: {
    fontFamily: fonts.semi_bold,
    fontSize: 16,
    color: '#0F0F0F',
    marginRight: scaledHeight(20),
    marginTop: scaledHeight(5),
    textAlign: 'right',
  },
});

export default styles;
